export const EXPERIENCE = [
    {
        id: "DAM",
        title: "CHE in Cross-Platform Application Development",
        type: 1,
        image: "https://st1.u-tad.com/media/2020/11/Ij8G0b_x_400x400.png",
        subtitle: "U-tad, Madrid. Sep 2018 - Jun 2020",
        description: "My firsts steps learning programming, it opened me a completely new world full of opportunities and paths, at this moment I couldn't resist the temptation of learn as much technologies a I could everything I see related with software development is awesome",
        technologies: "Java, Spring, Kotlin, Dart, HTML, CSS, Javascript, MongoDB, MySQL, PostgreSQL",
        placeLink: "https://u-tad.com/?utm_source=sem&utm_medium=search&utm_campaign=22-23-SEM-BRAND&cdest=both&ctype=paid&gclid=CjwKCAjw9NeXBhAMEiwAbaY4ll2JbmJkDCX7pH3ZKGpl_KvZzxtrkR_H7l6byskyY3Bp3cMBwzHqrRoCWS8QAvD_BwE",
    },
    {
        id: "ITP",
        title: "Internship as Programmer",
        type: 2,
        image: "https://www.sondasonora.com/wp-content/uploads/2019/01/maxvalley.png",
        subtitle: "U-tad, Madrid. Apr 2020 - Jun 2020",
        description: "During my internship here I learned the proccess of developing a product, we got to make a mobile game in 3 months, obviously this includes working with a team using GitHub for the respository and Slack for communicating with the team, we also had our daily meetings and milestones, etc...",
        technologies: "C#, Unity",
        placeLink: "https://maxvalley.com/",
    },
    {
        id: "MVP",
        title: "Master in Videogame Programming",
        type: 1,
        image: "https://st1.u-tad.com/media/2020/11/Ij8G0b_x_400x400.png",
        subtitle: "U-tad, Madrid. Oct 2020 - Oct 2021",
        description: "After doing my internship at Max Valley S.L, I got interested in the development of videogames so I decided to study this master at the same place I got my CHE and I learned a lot specially in controlling the memory addresses with the utilites of pointers",
        technologies: "C++, Unreal Engine, C#, Unity",
        placeLink: "https://u-tad.com/?utm_source=sem&utm_medium=search&utm_campaign=22-23-SEM-BRAND&cdest=both&ctype=paid&gclid=CjwKCAjw9NeXBhAMEiwAbaY4ll2JbmJkDCX7pH3ZKGpl_KvZzxtrkR_H7l6byskyY3Bp3cMBwzHqrRoCWS8QAvD_BwE",
    },
    {
        id: "VGP",
        title: "Videogame Programmer",
        type: 2,
        image: "../../../assets/media/frozenham.png",
        subtitle: "FrozenHam Studios, Madrid. Jan 2021 - Oct 2021",
        description: "As part of my Master's Dissertation we needed to found a videogame studio and also a videogame along with Art's Master & Design's Master, that's how FrozenHam Studios was born, and It's first game: Ronin-Hood Sisters in which I developed part of the Gameplay, UI and tools.",
        technologies: "C++, Unreal Engine, Jira",
        placeLink: "https://frozenham-studios.itch.io/",
    },
    {
        id: "FSW",
        title: "Fullstack developer",
        type: 1,
        image: "https://media-exp1.licdn.com/dms/image/C4D0BAQE-5bFBen0L5w/company-logo_200_200/0/1618306284208?e=2147483647&v=beta&t=aOsQgumQjoK64VmE4cs1l-U3H-MtlbsY4BWF7W7J7oE",
        subtitle: "Id Bootcamps, Madrid. May 2022 - Jul 2022",
        description: "A 3 Months long bootcamp fully centered in learning fullstack web development. I started making simples HTML and I ended up learning how to make bots in Telegram and building my own we application with a handmade API called Sport Share",
        technologies: "Angular, Typescript, HTML, CSS, NodeJS, Express, MySQL, MongoDB",
        placeLink: "https://iddigitalschool.com/bootcamps/",
    },

]
